[package]
name = "fetcher"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
main-api = { path = "../main-api", features = ["model-only"] }
# dto = { workspace = true, features = ["server"] }
serde.workspace = true
serde_json.workspace = true
bdk = { workspace = true, features = ["be"] }
# ethers-providers = "2.0.14"
# ethers-contract = "2.0.14"
# ethers-core = "2.0.14"
# ethers-middleware = "2.0.14"
# ethers = "2.0.14"
futures = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.41"
scraper = "0.23.1"
axum = { version = "0.8.1", features = ["macros"] }
chrono = "0.4.41"
teloxide = { version = "0.17.0", features = ["macros"] }
aws-config = "1.8.8"
aws-credential-types = "1.2.8"
aws-sdk-dynamodb = "1.96.0"

[features]
default = []
# server = ["dto/server"]
no-secret = []
